name: build-and-release

on:
  push:
    branches:
      - master

jobs:
  build-creator:
    name: Build & Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: DD-MM-YYYY

      - name: Setup Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup NDK
        uses: android-actions/setup-android@v3
        with:
          packages: "ndk;21.4.7075529"

      - name: Building with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 6.9
          arguments: 'build -x lint -Pandroid.ndkPath=/usr/local/lib/android/sdk/ndk/21.4.7075529'

      - name: Upload APK Files to Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Auto Build ${{ steps.current-time.outputs.formattedTime }}"
          tag_name: "v${{ github.run_number }}-${{ steps.current-time.outputs.formattedTime }}"
          prerelease: true
          body: |
            This is an Automatic Release by GitHub Actions.
            APK marked "unsigned" needs to be signed with test key before installing.
          files: |
            ./app/build/outputs/apk/**/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
